mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.shy.redis.client.entity
server:
  port: 8080
spring:
  application:
    name: redis-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: xxxx
    url: jdbc:mysql://localhost:3306/redis_config?serverTimezone=UTC
    username: xxxx
zookeeper:
  connect-string: ${zookeeper.host}:${zookeeper.port}
  session-timeout: 8000
  host: localhost
  port: 2181
redis:
  host: localhost
  port: 6379
  database: 0
  password:
logging:
  level:
    root: info
    com.shy.redis.client: debug